###POST
POST http://localhost:3004/api/notes
Content-Type: application/json

{
    "title": "NodeJs",
    "sections": [
        {
            "sectionTitle": "NodeJs Varios",
            "sectionNotes": [
                {
                    "noteTitle": "NodeJs 1",
                    "noteData": "https://axios-http.com/ - Axios library"
                },
                {
                    "noteTitle": "NodeJs 2",
                    "noteData": "https://jquery.com/ - JQuery library"
                },
                {
                    "noteTitle": "NodeJs 3",
                    "noteData": "https://reactrouter.com/ - React Router library"
                }
            ]
        }
    ]
}